apiVersion: apps/v1
kind: Deployment
metadata:
  name: chargers
  labels:
    app: chargers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chargers
  template:
    metadata:
      labels:
        app: chargers
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: chargers
          image: nicholasjackson/fake-service:v0.7.8
          ports:
            - containerPort: 9090
          env:
          - name: MESSAGE
            value: "Go LA Chargers!"
